### PR TITLE
Add cast templates

### PR DESCRIPTION
**Pull request by Coffee0127**
This PR add templates for cast or cast as post fix completions.

ezgif-5-8f2729f079

### CODE REVIEW

**Comment by ipatalas** [comment]
That's great! I love these templates.

Can you please fix failing tests? I'll merge it after that.

**Comment by Coffee0127** [comment]
@ipatalas fixed failing tests with 43f12133a4065dc17c0df1a68eab305bb23ccaa7
I am sorry for my carelessness :(

**Comment by ipatalas** [comment]
No worries. It happens. I will make a release later today.
Good job, thanks 👍

**Comment by Coffee0127** [comment]
Thanks @ipatalas 😆

**Pull request merged**
